# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Functions to do the decomposition by leveraging Intel MKL through RcppEigen
#'
#' \describe{
#' \item{\strong{fMatChol}}{This function performs the Cholesky decomposition of the matrix `X`,
#'  i.e., `X = L L^T`, where `L` is a lower triangular matrix with real
#'  and positive diagonal entries, and `L^T` is the transpose of `L`.}
#' \item{\strong{fMatLU}}{This function performs the LU decomposition of the matrix `X`, namely, `X = PLU`,
#'  where `L` is a lower triangular matrix with unit diagonal entries,
#'  `U` is an upper triangular matrix and `P` is a permutation matrix.}
#' \item{\strong{fMatQR}}{This function performs the QR decomposition of the matrix `X`, i.e., `X = QR`,
#'  where `Q` is an orthogonal matrix and `R` is an upper triangular matrix.}
#' \item{\strong{fMatSVD}}{This function performs the singular value decomposition (SVD) of the matrix `X`, namely, `X = U D V^T`,
#'  where `U` and `V` are orthogonal matrices and `D` is a diagonal matrix.}
#' \item{\strong{fMatEigen}}{This function performs the eigenvalue decomposition of the matrix `X`,
#'  i.e., `X = V D V^(-1)`, where 'V' is a matrix whose columns are the eigenvectors of 'X',
#'  and 'D' is a diagonal matrix whose entries are the corresponding eigenvalues of 'X'.}
#' \item{\strong{fMatEigen}}{This function returns a list of objects with two elements:  'values' and 'vectors',
#'  which are respectively the eigenvalues and eigenvectors of 'X'.}
#' }
#'
#' @param X The input matrix.
#' @rdname fast_matrix_decomposition
#' @name fast_matrix_decomposition
#' @examples
#' m <- matrix(c(5,1,1,3),2,2)
#' fMatChol(m)
#' all.equal(fMatChol(m), chol(m)) # It's the same to R
#'
#' X <- matrix(rnorm(9), 3, 3)
#' luRes <- fMatLU(X)
#' solve(luRes$P) %*% luRes$L %*% luRes$U # X = P^(-1) L U
#'
#' qrRes <- fMatQR(X)
#' qrRes$Q %*% qrRes$R # X = Q R
#'
#' hilbert <- function(n) { i <- 1:n; 1 / outer(i - 1, i, "+") }
#' X <- hilbert(9)[, 1:6]
#' (svdRes <- fMatSVD(X))
#' D <- diag(as.vector(svdRes$d))
#' svdRes$u[ , 1:6] %*% D %*% t(svdRes$v) #  X = U D V'
#' t(svdRes$u[ , 1:6]) %*% X %*% svdRes$v #  D = U' X V
#'
#' X <- hilbert(9)
#' eigenRes <- fMatEigen(X)
#' Re(eigenRes$vectors %*% diag(eigenRes$values) %*% solve(eigenRes$vectors)) # X = V D V^(-1)
#' @export
fMatChol <- function(X) {
    .Call('_oneMKL_MatrixCal_fMatChol', PACKAGE = 'oneMKL.MatrixCal', X)
}

#' @name fast_matrix_decomposition
#' @export
fMatLU <- function(X) {
    .Call('_oneMKL_MatrixCal_fMatLU', PACKAGE = 'oneMKL.MatrixCal', X)
}

#' @name fast_matrix_decomposition
#' @export
fMatQR <- function(X) {
    .Call('_oneMKL_MatrixCal_fMatQR', PACKAGE = 'oneMKL.MatrixCal', X)
}

#' @name fast_matrix_decomposition
#' @export
fMatSVD <- function(X) {
    .Call('_oneMKL_MatrixCal_fMatSVD', PACKAGE = 'oneMKL.MatrixCal', X)
}

#' @name fast_matrix_decomposition
#' @export
fMatEigen <- function(X) {
    .Call('_oneMKL_MatrixCal_fMatEigen', PACKAGE = 'oneMKL.MatrixCal', X)
}

#' Functions that use oneMKL for fast matrix calculations through RcppEigen
#'
#' \describe{
#' \item{\strong{fMatProd}}{This function returns the multiplication of matrices `X` and `Y`, i.e., `XY`.}
#' \item{\strong{fMatTransProd}}{This function returns the product of the transpose of the matrix `X`
#'  and the matrix `Y`, i.e., `X^T Y`.}
#' \item{\strong{fMatInv}}{This function returns the inverse of the matrix `X`, i.e., `X^(-1)`.
#'  If the matrix `X` is symmetric positive definite, Cholesky decomposition
#'  will be used for better computational performance.}
#' \item{\strong{fMatSolve}}{This function returns the solution of a linear system `AX=b`.
#'  If the matrix `X` is symmetric positive definite, Cholesky decomposition
#'  will be used for better computational performance.
#'  If the matrix `X` is invertible, the LU decomposition
#'  will be used for better computational performance.}
#' \item{\strong{fMatAdd}}{This function returns the sum of matrices `X` and `Y`, i.e., `X + Y`}
#' \item{\strong{fMatSubtract}}{This function returns the result of the matrix `X` minus the matrix `Y`, namely, `X - Y`.}
#' \item{\strong{fMatDet}}{This function returns the determinant of the matrix `X`.}
#' \item{\strong{fMatRank}}{This function returns the rank of the matrix `X`.}
#' \item{\strong{fMatRowSum}}{This function returns the sum of each row.}
#' \item{\strong{fMatColSum}}{This function returns the sum of each column.}
#' \item{\strong{fMatRowMin}}{This function returns the minimum of each row.}
#' \item{\strong{fMatRowMax}}{This function returns the maximum of each row.}
#' \item{\strong{fMatColMin}}{This function returns the minimum of each column.}
#' \item{\strong{fMatColMax}}{This function returns the maximum of each column.}
#' }
#'
#' @param X,Y The input matrices 'X' and 'Y'.
#' @return The corresponding results.
#'
#' @examples
#' x <- matrix(rnorm(1e4), 100)
#' y <- matrix(rnorm(1e2), 100)
#' z <- matrix(rnorm(1e4), 100)
#' XtX <- fMatProd(t(x), x)
#' XtX2 <- fMatTransProd(x, x)
#' all.equal(XtX, XtX2) # TRUE
#'
#' invXtX <- fMatInv(XtX)
#' fMatSolve(XtX, fMatTransProd(x, y)) # linear regression coefficients
#'
#' fMatAdd(x, z) # x + z
#' fMatSubtract(x, z) # x - z
#'
#' fMatDet(x)
#' fMatRank(x)
#'
#' fMatRowSum(x) # rowSums(x)
#' fMatRowMin(x) # apply(x, 1, min)
#' fMatRowMax(x) # apply(x, 1, max)
#' fMatColMin(x) # apply(x, 2, min)
#' fMatColMax(x) # apply(x, 2, max)
#' @rdname fast_matrix_ops
#' @name fast_matrix_ops
#' @export
fMatProd <- function(X, Y) {
    .Call('_oneMKL_MatrixCal_fMatProd', PACKAGE = 'oneMKL.MatrixCal', X, Y)
}

#' @name fast_matrix_ops
#' @export
fMatTransProd <- function(X, Y) {
    .Call('_oneMKL_MatrixCal_fMatTransProd', PACKAGE = 'oneMKL.MatrixCal', X, Y)
}

#' @param is_invertible A logical variable indicating whether the input matrix `X` is invertible.
#'  Better computational performance is expected if the matrix is invertible.
#' @param is_sym_pd A logical variable indicating whether the input matrix `X` is symmetric positive definitive.
#'  Better computational performance is expected if the matrix is symmetric positive definitive.
#' @name fast_matrix_ops
#' @export
fMatSolve <- function(X, Y, is_sym_pd = FALSE, is_invertible = FALSE) {
    .Call('_oneMKL_MatrixCal_fMatSolve', PACKAGE = 'oneMKL.MatrixCal', X, Y, is_sym_pd, is_invertible)
}

#' @name fast_matrix_ops
#' @export
fMatInv <- function(X, is_sym_pd = FALSE) {
    .Call('_oneMKL_MatrixCal_fMatInv', PACKAGE = 'oneMKL.MatrixCal', X, is_sym_pd)
}

#' @name fast_matrix_ops
#' @export
fMatAdd <- function(X, Y) {
    .Call('_oneMKL_MatrixCal_fMatAdd', PACKAGE = 'oneMKL.MatrixCal', X, Y)
}

#' @name fast_matrix_ops
#' @export
fMatSubtract <- function(X, Y) {
    .Call('_oneMKL_MatrixCal_fMatSubtract', PACKAGE = 'oneMKL.MatrixCal', X, Y)
}

#' @name fast_matrix_ops
#' @export
fMatRowSum <- function(X) {
    .Call('_oneMKL_MatrixCal_fMatRowSum', PACKAGE = 'oneMKL.MatrixCal', X)
}

#' @name fast_matrix_ops
#' @export
fMatColSum <- function(X) {
    .Call('_oneMKL_MatrixCal_fMatColSum', PACKAGE = 'oneMKL.MatrixCal', X)
}

#' @name fast_matrix_ops
#' @export
fMatRowMin <- function(X) {
    .Call('_oneMKL_MatrixCal_fMatRowMin', PACKAGE = 'oneMKL.MatrixCal', X)
}

#' @name fast_matrix_ops
#' @export
fMatColMin <- function(X) {
    .Call('_oneMKL_MatrixCal_fMatColMin', PACKAGE = 'oneMKL.MatrixCal', X)
}

#' @name fast_matrix_ops
#' @export
fMatRowMax <- function(X) {
    .Call('_oneMKL_MatrixCal_fMatRowMax', PACKAGE = 'oneMKL.MatrixCal', X)
}

#' @name fast_matrix_ops
#' @export
fMatColMax <- function(X) {
    .Call('_oneMKL_MatrixCal_fMatColMax', PACKAGE = 'oneMKL.MatrixCal', X)
}

#' @name fast_matrix_ops
#' @export
fMatDet <- function(X) {
    .Call('_oneMKL_MatrixCal_fMatDet', PACKAGE = 'oneMKL.MatrixCal', X)
}

#' @name fast_matrix_ops
#' @export
fMatRank <- function(X) {
    .Call('_oneMKL_MatrixCal_fMatRank', PACKAGE = 'oneMKL.MatrixCal', X)
}

#' @name fast_matrix_ops
#' @export
fMatRCond <- function(X) {
    .Call('_oneMKL_MatrixCal_fMatRCond', PACKAGE = 'oneMKL.MatrixCal', X)
}

#' Function to get the version of Intel MKL
#'
#' @return The version of Intel MKL
#' @examples
#' getMKLVersion()
#' @export
getMKLVersion <- function() {
    .Call('_oneMKL_MatrixCal_getMKLVersion', PACKAGE = 'oneMKL.MatrixCal')
}

#' Function to get/set the number of threads used in Intel MKL
#'
#' @param nThreads The number of threads you want to use in Intel MKL.
#' @return The number of threads.
#'
#' @examples
#' getMKLThreads() # Default is the number of CPUs cores on your PC
#'
#' \dontrun{
#' setMKLThreads(1)
#' getMKLThreads() # 1
#' }
#' @name mkl_threads
#' @export
setMKLThreads <- function(nThreads) {
    .Call('_oneMKL_MatrixCal_setMKLThreads', PACKAGE = 'oneMKL.MatrixCal', nThreads)
}

#' @name mkl_threads
#' @export
getMKLThreads <- function() {
    .Call('_oneMKL_MatrixCal_getMKLThreads', PACKAGE = 'oneMKL.MatrixCal')
}

